jobs:
  strategy:
    max-parallel: 1
    matrix:
      python_versions:
        - '3.6'
        - '3.7'
        - '3.8'
  run_tests:
    runs-on: ubuntu-latest
    services:
      vault:
        image: vault:1.7.3
        env:
          VAULT_DEV_ROOT_TOKEN_ID: "testing"
        ports:
          - 8200:8200
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python_versions }}
      - name: "flake8 run"
        run: |
          flake8
        with:
          python-version: "${{ matrix.python_versions }}
      - name: "run unit tests"
        run: |
          stestr run "^vaultlocker.tests.unit.*"
        with:
          python-version: "${{ matrix.python_versions }}
      - name: "run functional tests"
        run: |
          stestr run "^vaultlocker.tests.functional.*"
        with:
          python-version: "${{ matrix.python_versions }}
